### ISSUE TITLE
Can not execute example on readme

### ISSUE THREAD

**Issue by mql21** [RoxasShadow/Smogon#3]
I created a _test.rb_ file at the root of the cloned project with code provided in the readme:

```
require 'smogon'

puts Smogon::Pokedex.get    'Blaziken'
puts Smogon::Abilitydex.get 'Synchronize'
puts Smogon::Itemdex.get    'Leftovers'
puts Smogon::Movedex.get    'Extreme Speed'
puts Smogon::Movesetdex.get 'Abomasnow', 'UU', 'bw' 
```

but I'm getting the following error when I execute it:

_/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 404 Not Found (OpenURI::HTTPError)
        from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
        from /var/lib/gems/2.3.0/gems/smogon-0.6.2/lib/smogon/api.rb:34:in `request'
        from /var/lib/gems/2.3.0/gems/smogon-0.6.2/lib/smogon/pokedex.rb:37:in `get'
        from pokemon.rb:4:in `<main>'_

I have previously installed the gem but I can't seem to get it to work. Is this lib still working? Or am I doing something wrong?

Cheers.

**Comment by RoxasShadow** [comment]
Hi @miquelp,

I just run the tests and they're failing reporting the same errors you had. Checking the website, it looks like they replaced their HTTP APIs with new ones that are RPC-based.

We need to somehow implement them in this gem to make it work again.

**Comment by RoxasShadow** [comment]
https://github.com/RoxasShadow/Smogon/commit/4959fc801d5d42af4648f6c380688ba5fb57070f

Let me know if something is still not working for you.

**Comment by mql21** [comment]
It is now working like charm. Thanks for the fix.
